name: wakatracker_api
description: A REST API for the WakaTime.
version: 0.1.0

environment:
  sdk: ^3.0.6

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1

dependencies:
  dio: ^5.3.2
  freezed_annotation: ^2.4.1
  fresh_dio: ^0.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
