name: wakatracker_api
description: A REST API for the WakaTime.
version: 0.2.1

environment:
  sdk: ^3.0.6

dev_dependencies:
  args: ^2.7.0
  build_runner: ^2.4.6
  dart_style: ^3.0.0
  dotenv: ^4.2.0
  freezed: ^3.0.0
  json_serializable: ^6.7.1
  path: ^1.9.1
  retrofit_generator: ^9.0.0
  test: ^1.21.0
  very_good_analysis: ^7.0.0
  

dependencies:
  dio: ^5.3.2
  freezed_annotation: ^3.0.0
  fresh_dio: ^0.4.1
  json_annotation: ^4.9.0
  retrofit: ^4.0.1
